language: node_js
node_js:
- '7'
#before_install:
#- openssl aes-256-cbc -K $encrypted_0b980ef632b8_key -iv $encrypted_0b980ef632b8_iv
#  -in id_rsa.enc -out ~/.ssh/id_rsa -d
#- chmod 600 ~/.ssh/id_rsa
#- echo -e "Host 192.168.2.142\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
#addons:
#  ssh_known_hosts: 192.168.2.142
#after_success:
#- ssh root@192.168.2.142 'cd /home/testci && git clone https://github.com/wangxiansheng001/wang-cli.git'

# sfsdf
# init =/bin/sh

#language: node_js
#node_js:
#- 6.10.0
#after_script:
#- scp -o StrictHostKeyChecking=no ./src/app.js yideng:/root/code
#before_install:
#- openssl aes-256-cbc -K $encrypted_575687a1f022_key -iv $encrypted_575687a1f022_iv
 # -in id_rsa.enc -out id_rsa -d
#- mv id_rsa ~/.ssh -f
#- chmod 600 ~/.ssh/id_rsa
#- eval $(ssh-agent)
#- ssh-add ~/.ssh/id_rsa
#- cp .travis/ssh_config ~/.ssh/config