language: node_js
node_js:
- 7.6.0
after_script:
- scp -r -o StrictHostKeyChecking=no ./bin 139.199.72.81:/root/man
before_install:
- openssl aes-256-cbc -K $encrypted_586634722818_key -iv $encrypted_586634722818_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- chmod 600 ~/.ssh/config
